create extension if not exists pgcrypto;

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  enabled boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  id boolean primary key default true,
  site_name text not null default 'Zabit Hayat Tele',
  description text not null default 'Save this website for updates and new links.',
  purchase_title text not null default 'Purchase through Telegram',
  purchase_description text not null default 'Message us on Telegram to purchase or get more information.',
  purchase_link text not null default 'https://t.me/',
  telegram text not null default '',
  pinterest text not null default '',
  vk text not null default '',
  facebook text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  slot smallint not null unique check (slot between 1 and 8),
  title text not null default '',
  description text not null default '',
  link text not null default '#',
  media_url text,
  media_type text check (media_type in ('image','video') or media_type is null),
  media_path text,
  published boolean not null default true,
  updated_at timestamptz not null default now()
);

insert into public.site_settings(id) values(true) on conflict (id) do nothing;

insert into public.posts(slot,title,description,link)
select g, 'New Update '||lpad(g::text,2,'0'), 'Add your latest information, announcement or useful link here.','#'
from generate_series(1,8) g
on conflict (slot) do nothing;

alter table public.admins enable row level security;
alter table public.site_settings enable row level security;
alter table public.posts enable row level security;

-- Public visitors can read published site content.
create policy "public read settings"
on public.site_settings for select using (true);

create policy "public read published posts"
on public.posts for select using (published = true);

-- Admin access.
create policy "admins can read admin table"
on public.admins for select
using (auth.uid() = user_id);

create policy "admins can manage settings"
on public.site_settings for all
using (exists(select 1 from public.admins a where a.user_id=auth.uid() and a.enabled=true))
with check (exists(select 1 from public.admins a where a.user_id=auth.uid() and a.enabled=true));

create policy "admins can manage posts"
on public.posts for all
using (exists(select 1 from public.admins a where a.user_id=auth.uid() and a.enabled=true))
with check (exists(select 1 from public.admins a where a.user_id=auth.uid() and a.enabled=true));

-- Storage bucket.
insert into storage.buckets(id,name,public)
values('media','media',true)
on conflict (id) do update set public=true;

create policy "public can view media"
on storage.objects for select
using (bucket_id='media');

create policy "admins can upload media"
on storage.objects for insert
with check (
  bucket_id='media'
  and exists(select 1 from public.admins a where a.user_id=auth.uid() and a.enabled=true)
);

create policy "admins can update media"
on storage.objects for update
using (
  bucket_id='media'
  and exists(select 1 from public.admins a where a.user_id=auth.uid() and a.enabled=true)
)
with check (
  bucket_id='media'
  and exists(select 1 from public.admins a where a.user_id=auth.uid() and a.enabled=true)
);

create policy "admins can delete media"
on storage.objects for delete
using (
  bucket_id='media'
  and exists(select 1 from public.admins a where a.user_id=auth.uid() and a.enabled=true)
);
